name: frappe_dart
description: A comprehensive Dart wrapper for interacting with the Frappe API, providing easy access to its features and enabling seamless communication with Frappe-based systems.
version: 0.0.6
homepage: https://github.com/kinetsystems/frappe_dart
repository: https://github.com/kinetsystems/frappe_dart
issue_tracker: https://github.com/kinetsystems/frappe_dart/issues
topics:
  - frappe
  - api
  - dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  socket_io_client: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  mockito: ^5.4.4
  test: ^1.25.8
  very_good_analysis: ">=9.0.0 <11.0.0"
